# Generated by Django 4.2.3 on 2023-09-10 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallery',
            name='hours',
            field=models.CharField(max_length=15),
        ),
    ]
