# Generated by Django 4.2.3 on 2023-09-16 06:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_alter_gallery_hours'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exhibition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('closingDate', models.DateField()),
                ('description', models.TextField(max_length=200)),
                ('feedback', models.TextField(max_length=250)),
                ('gallery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.gallery')),
            ],
        ),
    ]
