# Generated by Django 4.2.3 on 2023-09-22 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_exhibition_user_alter_exhibition_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='exhibition',
            name='user_favourite',
            field=models.BooleanField(default=False),
        ),
    ]
